-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 20:32:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema s202_n3ex1_SPOTIFY
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema s202_n3ex1_SPOTIFY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s202_n3ex1_SPOTIFY` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `s202_n3ex1_SPOTIFY`.`usuario_free`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s202_n3ex1_SPOTIFY`.`usuario_free` (
  `idusuario_free` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `sexo` ENUM('H', 'M') NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `identificador_usuario` INT NOT NULL,
  `lista_compartida_idlista_compartida` INT NOT NULL,
  PRIMARY KEY (`idusuario_free`),
  UNIQUE INDEX `identificador_usuario_UNIQUE` (`identificador_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_free_lista_compartida_idx` (`lista_compartida_idlista_compartida` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_free_lista_compartida`
    FOREIGN KEY (`lista_compartida_idlista_compartida`)
    REFERENCES `mydb`.`lista_compartida` (`idlista_compartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist_usuario` (
  `idplaylist_usiario` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `nombreCancion` VARCHAR(45) NOT NULL,
  `identificador_playlistUsuario` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  `usuario_free_idusuario_free` INT NOT NULL,
  PRIMARY KEY (`idplaylist_usiario`),
  UNIQUE INDEX `identificador_UNIQUE` (`identificador_playlistUsuario` ASC) VISIBLE,
  UNIQUE INDEX `fecha_creacion_UNIQUE` (`fecha_creacion` ASC) VISIBLE,
  INDEX `fk_playlist_usuario_usuario_premiun1_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  INDEX `fk_playlist_usuario_usuario_free1_idx` (`usuario_free_idusuario_free` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_usuario_usuario_premiun1`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_usuario_usuario_free1`
    FOREIGN KEY (`usuario_free_idusuario_free`)
    REFERENCES `s202_n3ex1_SPOTIFY`.`usuario_free` (`idusuario_free`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_compartida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lista_compartida` (
  `idlista_compartida` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `fecha_queComparte` VARCHAR(45) NOT NULL,
  `lista_compartidacol` DATE NOT NULL,
  `playlist_usuario_idplaylist_usiario` INT NOT NULL,
  PRIMARY KEY (`idlista_compartida`),
  INDEX `fk_lista_compartida_playlist_usuario1_idx` (`playlist_usuario_idplaylist_usiario` ASC) VISIBLE,
  CONSTRAINT `fk_lista_compartida_playlist_usuario1`
    FOREIGN KEY (`playlist_usuario_idplaylist_usiario`)
    REFERENCES `mydb`.`playlist_usuario` (`idplaylist_usiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_premiun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_premiun` (
  `idusuario_premiun` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `sexo` ENUM('H', 'M') NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `identificador_premium` INT NOT NULL,
  `lista_compartida_idlista_compartida` INT NOT NULL,
  PRIMARY KEY (`idusuario_premiun`),
  UNIQUE INDEX `identificador_premium_UNIQUE` (`identificador_premium` ASC) VISIBLE,
  INDEX `fk_usuario_premiun_lista_compartida1_idx` (`lista_compartida_idlista_compartida` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_premiun_lista_compartida1`
    FOREIGN KEY (`lista_compartida_idlista_compartida`)
    REFERENCES `mydb`.`lista_compartida` (`idlista_compartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suscripcion_premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suscripcion_premium` (
  `idsuscripcion_premium` INT NOT NULL AUTO_INCREMENT,
  `inicio_suscripcion` DATE NOT NULL,
  `renovacion_servicio` DATE NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  PRIMARY KEY (`idsuscripcion_premium`),
  INDEX `fk_suscripcion_premium_usuario_premiun_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  CONSTRAINT `fk_suscripcion_premium_usuario_premiun`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_pagos` (
  `idregistro_pagos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `numero_orden` INT NOT NULL,
  `total` FLOAT NOT NULL,
  `pago_premium_idpago_premium` INT NOT NULL,
  PRIMARY KEY (`idregistro_pagos`),
  UNIQUE INDEX `numero_orden_UNIQUE` (`numero_orden` ASC) VISIBLE,
  INDEX `fk_registro_pagos_pago_premium1_idx` (`pago_premium_idpago_premium` ASC) VISIBLE,
  CONSTRAINT `fk_registro_pagos_pago_premium1`
    FOREIGN KEY (`pago_premium_idpago_premium`)
    REFERENCES `mydb`.`pago_premium` (`idpago_premium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago_premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago_premium` (
  `idpago_premium` INT NOT NULL AUTO_INCREMENT,
  `tarjeta_credito` TINYINT(1) NOT NULL,
  `paypal` TINYINT(1) NOT NULL,
  `suscripcion_premium_idsuscripcion_premium` INT NOT NULL,
  `registro_pagos_idregistro_pagos` INT NOT NULL,
  PRIMARY KEY (`idpago_premium`),
  INDEX `fk_pago_premium_suscripcion_premium1_idx` (`suscripcion_premium_idsuscripcion_premium` ASC) VISIBLE,
  INDEX `fk_pago_premium_registro_pagos1_idx` (`registro_pagos_idregistro_pagos` ASC) VISIBLE,
  CONSTRAINT `fk_pago_premium_suscripcion_premium1`
    FOREIGN KEY (`suscripcion_premium_idsuscripcion_premium`)
    REFERENCES `mydb`.`suscripcion_premium` (`idsuscripcion_premium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_premium_registro_pagos1`
    FOREIGN KEY (`registro_pagos_idregistro_pagos`)
    REFERENCES `mydb`.`registro_pagos` (`idregistro_pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago_tarjetaCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago_tarjetaCredito` (
  `idpago_tarjetaCredito` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` INT NOT NULL,
  `mes_añoCaducidad` DATE NOT NULL,
  `codigo_seguridad` INT NOT NULL,
  `registro_pagos_idregistro_pagos` INT NOT NULL,
  `pago_premium_idpago_premium` INT NOT NULL,
  PRIMARY KEY (`idpago_tarjetaCredito`),
  INDEX `fk_pago_tarjetaCredito_registro_pagos1_idx` (`registro_pagos_idregistro_pagos` ASC) VISIBLE,
  INDEX `fk_pago_tarjetaCredito_pago_premium1_idx` (`pago_premium_idpago_premium` ASC) VISIBLE,
  CONSTRAINT `fk_pago_tarjetaCredito_registro_pagos1`
    FOREIGN KEY (`registro_pagos_idregistro_pagos`)
    REFERENCES `mydb`.`registro_pagos` (`idregistro_pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_tarjetaCredito_pago_premium1`
    FOREIGN KEY (`pago_premium_idpago_premium`)
    REFERENCES `mydb`.`pago_premium` (`idpago_premium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago_paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago_paypal` (
  `idpago_paypal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `registro_pagos_idregistro_pagos` INT NOT NULL,
  `pago_premium_idpago_premium` INT NOT NULL,
  PRIMARY KEY (`idpago_paypal`),
  INDEX `fk_pago_paypal_registro_pagos1_idx` (`registro_pagos_idregistro_pagos` ASC) VISIBLE,
  INDEX `fk_pago_paypal_pago_premium1_idx` (`pago_premium_idpago_premium` ASC) VISIBLE,
  CONSTRAINT `fk_pago_paypal_registro_pagos1`
    FOREIGN KEY (`registro_pagos_idregistro_pagos`)
    REFERENCES `mydb`.`registro_pagos` (`idregistro_pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_paypal_pago_premium1`
    FOREIGN KEY (`pago_premium_idpago_premium`)
    REFERENCES `mydb`.`pago_premium` (`idpago_premium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_playlist` (
  `idtipos_playlist` INT NOT NULL AUTO_INCREMENT,
  `activas` TINYINT(1) NOT NULL,
  `usuario_free_idusuario_free` INT NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  PRIMARY KEY (`idtipos_playlist`),
  INDEX `fk_tipos_playlist_usuario_free1_idx` (`usuario_free_idusuario_free` ASC) VISIBLE,
  INDEX `fk_tipos_playlist_usuario_premiun1_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  CONSTRAINT `fk_tipos_playlist_usuario_free1`
    FOREIGN KEY (`usuario_free_idusuario_free`)
    REFERENCES `s202_n3ex1_SPOTIFY`.`usuario_free` (`idusuario_free`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipos_playlist_usuario_premiun1`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_lista_borrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_lista_borrada` (
  `idtipo_lista_borrada` INT NOT NULL AUTO_INCREMENT,
  `fecha_baja` DATE NOT NULL,
  `usuario_free_idusuario_free` INT NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  PRIMARY KEY (`idtipo_lista_borrada`),
  INDEX `fk_tipo_lista_borrada_usuario_free1_idx` (`usuario_free_idusuario_free` ASC) VISIBLE,
  INDEX `fk_tipo_lista_borrada_usuario_premiun1_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_lista_borrada_usuario_free1`
    FOREIGN KEY (`usuario_free_idusuario_free`)
    REFERENCES `s202_n3ex1_SPOTIFY`.`usuario_free` (`idusuario_free`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_lista_borrada_usuario_premiun1`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `numero_identificador` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen_artista` VARCHAR(45) NOT NULL,
  `usuario_free_idusuario_free` INT NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  PRIMARY KEY (`idartista`),
  UNIQUE INDEX `numero_identificador_UNIQUE` (`numero_identificador` ASC) VISIBLE,
  INDEX `fk_artista_usuario_free1_idx` (`usuario_free_idusuario_free` ASC) VISIBLE,
  INDEX `fk_artista_usuario_premiun1_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  CONSTRAINT `fk_artista_usuario_free1`
    FOREIGN KEY (`usuario_free_idusuario_free`)
    REFERENCES `s202_n3ex1_SPOTIFY`.`usuario_free` (`idusuario_free`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artista_usuario_premiun1`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `año_publicacion` DATE NOT NULL,
  `imagen_portada` VARCHAR(45) NOT NULL,
  `identificador_album` INT NOT NULL,
  `artista_idartista` INT NOT NULL,
  PRIMARY KEY (`idalbum`),
  UNIQUE INDEX `idalbum_UNIQUE` (`idalbum` ASC) VISIBLE,
  UNIQUE INDEX `identificador_album_UNIQUE` (`identificador_album` ASC) VISIBLE,
  INDEX `fk_album_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `mydb`.`artista` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canciones` (
  `idcanciones` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `duracion_cancion` FLOAT NOT NULL,
  `numero_reproducciones` DOUBLE NOT NULL,
  `identificador_cancion` INT NULL,
  `cancionescol` VARCHAR(45) NOT NULL,
  `album_idalbum` INT NOT NULL,
  PRIMARY KEY (`idcanciones`),
  UNIQUE INDEX `idcanciones_UNIQUE` (`idcanciones` ASC) VISIBLE,
  UNIQUE INDEX `cancionescol_UNIQUE` (`cancionescol` ASC) VISIBLE,
  INDEX `fk_canciones_album1_idx` (`album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoritas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favoritas` (
  `idFavoritas` INT NOT NULL AUTO_INCREMENT,
  `nombre _albunes` VARCHAR(45) NOT NULL,
  `nombre_canciones` VARCHAR(45) NOT NULL,
  `usuario_premiun_idusuario_premiun` INT NOT NULL,
  `usuario_free_idusuario_free` INT NOT NULL,
  PRIMARY KEY (`idFavoritas`),
  INDEX `fk_Favoritas_usuario_premiun1_idx` (`usuario_premiun_idusuario_premiun` ASC) VISIBLE,
  INDEX `fk_Favoritas_usuario_free1_idx` (`usuario_free_idusuario_free` ASC) VISIBLE,
  CONSTRAINT `fk_Favoritas_usuario_premiun1`
    FOREIGN KEY (`usuario_premiun_idusuario_premiun`)
    REFERENCES `mydb`.`usuario_premiun` (`idusuario_premiun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritas_usuario_free1`
    FOREIGN KEY (`usuario_free_idusuario_free`)
    REFERENCES `s202_n3ex1_SPOTIFY`.`usuario_free` (`idusuario_free`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `s202_n3ex1_SPOTIFY` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
